server:
  port: 9999


spring:
  datasource:
    url: jdbc:mysql://123.207.253.16:3306/miaosha?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 123.207.253.16
    port: 6379
    password: weimin
  rabbitmq:
    host: 123.207.253.16
    port: 5672
    username: root
    password: root
    virtual-host: /java
    publisher-confirms: true

mybatis:
  mapper-locations: classpath:/mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

