server:
  port: 9090

dubbo:
  application:
    name: web-center
  registry:
    protocol: zookeeper
    address: 123.207.253.16:2181

spring:
  thymeleaf:
    cache: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    date-format: yyyy-MM-dd
  rabbitmq:
    host: 123.207.253.16
    port: 5672
    username: root
    password: root
    virtual-host: /java
    publisher-confirms: true
    publisher-returns: true

fdfs:
  so-timeout: 1500
  connect-timeout: 600
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list: 123.207.253.16:22122

images:
  serverPath: http://123.207.253.16:88/
